### PR TITLE
de.po: Updated

### PR DESCRIPTION
**Pull request by erwn16**
Gaps were closed, commas corrected, old-fashioned expressions updated, no points at the end of sentences

### CODE REVIEW

**Comment by erwn16** [comment]
Hello I am new on Github,
I really like the Cinnamenu and use it. So I contributed.
If this way of contributing is wrong - sorry.

**Comment by fredcw** [comment]
Your timing is very unlucky because just this morning I updated the files and created a new pull request. https://github.com/linuxmint/cinnamon-spices-applets/pull/3118 . Also, this version of Cinnamenu is an old version which I leave here so that people can leave me comments. The current version is always at https://github.com/linuxmint/cinnamon-spices-applets/tree/master/Cinnamenu%40json/files/Cinnamenu%40json . However, because I just updated the ,po files and my pull request hasn't been merged yet, the most recent version of de.po that I submitted today is here: https://github.com/linuxmint/cinnamon-spices-applets/blob/035be4380d59aa147535a30bc608dda6c3254664/Cinnamenu%40json/files/Cinnamenu%40json/po/de.po . The thing to do is wait until tomorrow when the PR is merged, make any changes you like to the new version and then do a PR like you did here but at the linux mint github https://github.com/linuxmint/cinnamon-spices-applets . All translation updates are automatically approved by the Linux Mint team there. See at the bottom of that last page:

>Pull requests from other people
...
>If the pull request adds translations it will likewise be merged. These are not going to effect the functionality of the code, and will make the applet available to many users who couldn't use it before due to a language barrier. We view this a essentially a bugfix...

Thanks for your help and I'm glad you like the applet.

**Comment by fredcw** [comment]
@erwn16 Sorry, I forgot to ping you in last comment.

**Comment by fredcw** [comment]
@erwn16 Update! My PR has just been merged so you can now make changes to the new version https://github.com/linuxmint/cinnamon-spices-applets/tree/master/Cinnamenu%40json/files/Cinnamenu%40json/po

**Comment by fredcw** [comment]
@erwm16 I'll add your changes to de.po. They'll appear in the next update. Thanks.

**Comment by erwn16** [comment]
@fredcw Hello fredcw,
Thank you for your fast response and numerous information.

To give a feedback
The updated de.po was only used after a new installation of Cinnamenu.
The category "Web-Bookmarks" is empty although there are bookmarks stored in the latest version of Firefox.
The context menus of the apps disappear from a size of 33 and more for icons of categories.

I launched an updated de.po file a few minutes ago.

Kind regards,
erwn16

**Comment by fredcw** [comment]
@erwn16 Thanks.
>The updated de.po was only used after a new installation of Cinnamenu.

Yes, I had a problem with this too. It seems that cinnamon maybe caches the po files and doesn't read them again until either the applet is updated through the applets dialogue or it is removed and added to the panel again.

Yes, the firefox bookmarks don't work. I need to fix this.

>The context menus of the apps disappear from a size of 33 and more for icons of categories.

I can't replicate this right now, I will check with german version.

**Comment by erwn16** [comment]
@fredcw No context menu: I attached a pdf with two screenshots. Kind regards, erwn16

[cinnamenu_no_context_menu.pdf](https://github.com/fredcw/Cinnamenu.json/files/4943965/cinnamenu_no_context_menu.pdf)

**Pull request closed without merging**
